# Permalinks
permalink:        pretty

# Compile CSS
sass:
  style: compressed
sass:
  sass_dir: _sass

# Setup
title:            Ease of use prototype
tagline:          'The design system for Asana Product Design'
url:              http://design.asana.biz
baseurl:          /
